// <auto-generated />
using IT3047Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IT3047Final.Migrations.Trail
{
    [DbContext(typeof(TrailContext))]
    [Migration("20201210193851_trailinit")]
    partial class trailinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("IT3047Final.Models.Trail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("parkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trailName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trailRating")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Trails");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            parkName = "Daniel Boone National Forest",
                            trailName = "Van Hook Falls and Cane Creek Valley",
                            trailRating = 4
                        },
                        new
                        {
                            ID = 2,
                            parkName = "Daniel Boone National Forest",
                            trailName = "Gray's Arch Trail Loop",
                            trailRating = 4
                        },
                        new
                        {
                            ID = 3,
                            parkName = "Daniel Boone National Forest",
                            trailName = "Sky Bridge Red River Gorge",
                            trailRating = 5
                        },
                        new
                        {
                            ID = 4,
                            parkName = "Daniel Boone National Forest",
                            trailName = "Double Arch Trail",
                            trailRating = 5
                        },
                        new
                        {
                            ID = 5,
                            parkName = "Little Miami State Park",
                            trailName = "Little Miami Scenic Trail",
                            trailRating = 4
                        },
                        new
                        {
                            ID = 6,
                            parkName = "Keehner Park",
                            trailName = "Keehner Park Trail",
                            trailRating = 3
                        },
                        new
                        {
                            ID = 7,
                            parkName = "Pine Hill Park",
                            trailName = "Pine Trails",
                            trailRating = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
